from pathlib import Path
from pymake.common.cmake_version import ECMakeVersion
from pymake.helpers.caller_info import CallerInfo
from pymake.generation.basic_generator import BasicGenerator
from pymake.generation.build_script import BuildScript

class CMake:
    """
    Primary class used to generate CMake build scripts.
    """
    def __init__(self,
        min_version: ECMakeVersion,
        generated_tree_path: str = "./.pymake"):
        """
        Initializes the object.
        @param min_version Minimum CMake version for the build scripts.
        @param generated_tree_path Path to the folder where all CMake build
          scripts generated by PyMake will be placed. If this is a relative
          path, it will be interpreted relative to the path of the script
          invoking this method.
        """
        self._min_version = min_version
        self._call_site = CallerInfo()

        # Path to the top level folder for the project
        self._source_tree_path = Path(self._call_site.file_path).parent

        # Use the folder containing the script constructing this object as the
        #   base path for the project. All other paths will be processed as
        #   paths relative to this path.
        if Path(generated_tree_path).is_absolute():
            generated_tree_abs_path = generated_tree_path
        else:
            generated_tree_abs_path = Path.joinpath(
                self._source_tree_path,
                Path(generated_tree_path)
            ).resolve()

        # Build script for the top-level CMakeLists.txt
        top_level_build_script = BuildScript(
            "CMakeLists.txt",
            "",
            str(generated_tree_abs_path)
        )
        top_level_build_script.add_generator(BasicGenerator(
            f"cmake_minimum_required(VERSION {min_version.to_version_string()})",
            caller_offset=1
        ))

        # Store all build script instances, indexed by the relative path of the
        #   file the build script instance is for
        self._build_scripts = {
            "": top_level_build_script
        }

    def build(self, generate_first: bool = True) -> None:
        """
        Builds the project via CMake.
        @param generate_first Whether `generate()` should be called before
          running the build. This should generally be left unchanged unless
          a call to `generate()` is made before this method is called (or using
          old versions of generated build scripts is acceptable).
        @throws RuntimeError Thrown if the build fails for any reason. Output
          from CMake will have been written to stdout and/or stderr, which
          should contain the error that was encountered.
        """
        if generate_first:
            self.generate()

    def generate(self) -> None:
        """
        Generates the build scripts for the project.
        """
        # Temporary - print the generated file's contents instead of writing
        #   them to disk
        for build_script in self._build_scripts.values():
            print(f"File: {build_script.target_path}")
            print("========================================")
            print(build_script.generate_file_contents(self._source_tree_path))
            print("========================================")
            print()
