# Site properties
site_name: "PyMake Documentation"

# Repository info
repo_url: https://github.com/MYTX-Wildfire/PyMake

# Navigation
nav:
  - Home: index.md
  - PyMake Reference:
      - 'Links': 'pymake/links.md'
      - 'Classes':
          - 'Class List': 'pymake/annotated.md'
          - 'Class Index': 'pymake/classes.md'
          - 'Class Hierarchy': 'pymake/hierarchy.md'
          - 'Class Members': 'pymake/class_members.md'
          - 'Class Member Functions': 'pymake/class_member_functions.md'
          - 'Class Member Variables': 'pymake/class_member_variables.md'
          - 'Class Member Typedefs': 'pymake/class_member_typedefs.md'
          - 'Class Member Enumerations': 'pymake/class_member_enums.md'
      - 'Namespaces':
          - 'Namespace List': 'pymake/namespaces.md'
          - 'Namespace Members': 'pymake/namespace_members.md'
          - 'Namespace Member Functions': 'pymake/namespace_member_functions.md'
          - 'Namespace Member Variables': 'pymake/namespace_member_variables.md'
          - 'Namespace Member Typedefs': 'pymake/namespace_member_typedefs.md'
          - 'Namespace Member Enumerations': 'pymake/namespace_member_enums.md'
      - 'Functions': 'pymake/functions.md'
      - 'Variables': 'pymake/variables.md'
      - 'Macros': 'pymake/macros.md'
      - 'Files': 'pymake/files.md'

# Theme properties
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - search
    - search.suggest

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

# mkdocs plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      # If this is not set, then this plugin will error out when trying to get
      #   date information for the autogenerated doxygen markdown files
      fallback_to_build_date: true
  - mkdoxy:
      projects:
        pymake:
          src-dirs: source/pymake
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            RECURSIVE: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True
