name: Run tests and measure code coverage

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.devcontainer/gh-actions.dockerfile
        push: false
        tags: pymake:latest

    - name: Start docker container
      run: docker run --rm -itd --name pymake pymake:latest

    - name: Run unit tests
      run: >
        docker exec pymake
        pytest --cov=pymake --cov-branch --cov-report=xml tests/unit

    - name: Run integration tests
      run: >
        docker exec pymake
        pytest --cov=pymake --cov-branch --cov-report=xml tests/integration

    - name: Report code coverage
      run: >
        docker exec pymake
        coverage report --show-missing
      if: success()

    - name: Stop docker container
      run: docker stop pymake
