name: Run tests and measure code coverage

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.devcontainer/gh-actions.dockerfile
        push: false
        tags: pymake:latest

    - name: Start docker container
      run: >
        docker run --rm -itd --name pymake -v "$GITHUB_WORKSPACE:/repo"
        --env PYTHONPATH="/repo/source"
        pymake:latest

    - name: Run unit tests
      run: >
        docker exec -w "/repo" pymake
        pytest --cov=pymake --cov-branch --cov-report=xml tests/unit

    - name: Run integration tests
      run: >
        docker exec -w "/repo" pymake
        pytest --cov=pymake --cov-branch --cov-report=xml --cov-append
        tests/integration

    - name: Dump code coverage
      run: >
        docker exec -w "/repo" pymake
        coverage report --show-missing
      if: success()

    - name: Record code coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: $GITHUB_WORKSPACE/coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '75 90'

    - name: Stop docker container
      run: docker stop pymake
